# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"

x-uffizzi:
  ingress:
    service: wiki
    port: 3000

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M

  wiki:
    image: "${WIKI_IMAGE}"
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000"
    deploy:
      resources:
        limits:
          memory: 500M

